# Module 5 - Kilowatthours

# TASK DESCRIPTION
# Prepare a function that based on working time, quantity
# consumed kilowatt-hours will answer how much I will pay for electricity, which
# consumes the device. The default cost of 1 kWh is 0.617

# Import libraries

# Welcome message
print('\nWelcome in "Kilowatthours" app.\n')

# Get data from user
g_working_time = float(input("Give me number of working time of device in hours: "))
g_device_power = float(input("Give me power of your device in kW: "))


# Testing data
# g_working_time = 12
# g_device_power = 0.6
# print(f'\nProgram will calculate cost device with power = {g_device_power} kW generates in {g_working_time} h.')

# Declare variables
cost_of_kWh = 0.617


# Declare function
def electricity_cost(dev_pow: float, work_time: float, cost_fact: float = cost_of_kWh) -> float:
    """
    This function takes device power and its working time to return electricity cost
    :param dev_pow: Power of device in kWh
    :param work_time: Number of working time in hours
    :param cost_fact: Cost of one kWh
    :return: Cost of electricity generated by device
    """
    return dev_pow * work_time * cost_fact


# Call function
ans = electricity_cost(dev_pow=g_device_power, work_time=g_working_time)

# Quit if wrong operation

# Process

# Print output message
print(f'\nElectricity will cost {ans:.2f}zł.\n')
